---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
